### ISSUE TITLE
[BUG] Chip is always crashing

### ISSUE THREAD

**Issue by zyojv** [Rusketh/ExpAdv3#14]
**How many people are experiencing it**
Only me right now

**Please describe in brief the issue you are experiencing:**
When i spawn a exp 3 the is always printing me out "One of your Expression3 gate's has errored (see golem console)."

Exp3 Code:
`system.print("hi");`

Yeah, thats my code!

Debug native output:
`
return 1 ( , env )                     
setfenv env ) function ( 
 _FUN["system.print(...)"] ( CONTEXT "s" { , , "hi" } ) ;   
end 
`

**Comment by zyojv** [comment]
Sorry i forgot the code printed out in the console!

`PREFIX	return
PREFIX	1
PREFIX	(
PREFIX	,
PREFIX	env
PREFIX	)
PREFIX	setfenv
PREFIX	env
PREFIX	)
PREFIX	function
PREFIX	(
PREFIX	
POSTFIX	print
KEEP	(
POSTFIX	(
POSTFIX	(
POSTFIX	(
POSTFIX	(
POSTFIX	(
KEEP	"hi"
POSTFIX	"hi"
KEEP	)
KEEP	;
POSTFIX	;
`

**Comment by Rusketh** [comment]
This project is no where near done and is currently not usable.

Sorry but your have to wait till we can start developing it again.

**Comment by Rusketh** [comment]
This issue was with the old compiler placing tokens in the incorrect order. We have since addressed this issue with an updated compiler.
