### ISSUE TITLE
[BUG] Entity (variables) don't work with applyForce();

### ISSUE THREAD

**Issue by trainspotexe** [Rusketh/ExpAdv3#17]
1. If you wish to alert us of more than one issue or request please submit them separately!
2. Please make sure that any long quotes of text (e.g code) should be submitted in the form of a [gist](gist.github.com) link.
3. Check that your request / issue has not already been mentioned, if it has please comment on the existing page instead.
4. If this is a request, please clear the template below and provide your request in as much detail as possible.
5. Please fill out the following template as accurately as possible:
    1. Have you checked it with the latest version of the repository:
    If no, please do so and if you are not on the latest version, please update and re-test.
Yes (development and stable)
    2. How many people are experiencing it (to your knowledge, including yourself):
N/A (don't know)
    3. Please describe in brief the issue you are experiencing:
Entity variables don't seem to work with applyForce (system.getEntity() produces a similar result when used in place of an entity variable which is assigned to system.getEntity() )
    4. If your getting any errors in game console, please provide them below.
N/A
    5. If your getting either a tokenizer, parser, compiler or internal error, please provide that below.
Warning Compiler Error: Unexpected symbol found (var) at line 5 char 12
    5.1 Please provide a [gist](gist.github.com) link to your code.
[here](https://gist.github.com/trainspotexe/9430e582e92d53da136917f2f72cc2e3)
    5.2 Please run the validation debugger and provide screenshots of the output tab. You can do this by right-clicking the validation bar and selecting "Validate and debug".
(no such option when right-clicking the validation bar)
    6. Please make sure to prefix your title with either [BUG] for issues or [REQ] for requests, as well as attaching any suitable labels.
done
    7. Is this issue linked to a specific code you are trying to execute:
Not that I know of

**Comment by Rusketh** [comment]
Ah, your using a colon instead of a period for the method operator.
