### ISSUE TITLE
Remove entity error

### ISSUE THREAD

**Issue by Rusketh** [Rusketh/ExpAdv3#30]
Reported by a workshop user, noting it here.

[Expression 3] lua/entities/wire_expression3_base/shared.lua:95: attempt to call method 'ExecuteInstance' (a nil value)
  1. cb - lua/entities/wire_expression3_base/shared.lua:95
   2. unknown - lua/expression3/expr_lib.lua:1471

[Expression 3] lua/entities/wire_expression3_base/shared.lua:95: attempt to call method 'ExecuteInstance' (a nil value)
  1. cb - lua/entities/wire_expression3_base/shared.lua:95
   2. unknown - lua/expression3/expr_lib.lua:1471

**Comment by oskar94** [comment]
Was fixed with commit https://github.com/Rusketh/ExpAdv3/commit/c575c6cd09448eb45421eaaa4b02efc4280f95ab

**Comment by Rusketh** [comment]
It was?
