### ISSUE TITLE
[BUG] Exponents can crash server

### ISSUE THREAD

**Issue by Scors4** [Rusketh/ExpAdv3#32]
Using an exponent on a piece of a vector causes instability.  It crashes the multiplayer server I've used it on, but it doesn't crash singleplayer (the chip self-deletes instead.)

Replication: put code on chip, unfreeze chip.
Code:

function void Main() {
    server {
        global entity E = system.getEntity();
        global vector TPos = E.getPos() + vector(0,0,50);
    }
}

function void Loop() {
    server {
        vector v = (TPos - E.getPos());
        if((v.x > 0.5) || (v.x < -0.5)) v.x = v.x ^ 0.85
        if((v.y > 0.5) || (v.y < -0.5)) v.y = v.y ^ 0.85
        if((v.z > 0.5) || (v.z < -0.5)) v.z = v.z ^ 0.85
        v = v * E.getMass();
        E.applyForce(v);
    }
}

event.add("Think", "Loop", Loop);
Main();

**Comment by ComposerFreak** [comment]
Thanks for the report, should be fixed in the next update.
