### ISSUE TITLE
[BUG] Cannot break from try/catch statement

### ISSUE THREAD

**Issue by Scors4** [Rusketh/ExpAdv3#33]
As the title suggests, attempting to break from the catch portion of a try/catch statement will result in this validation error:
  Warning Compiler Error: Break must not appear outside of a loop at line XX char YY

simple example:

```
table arr = new table(entity);
while(true)
{
    try {
        entity e=arr.popentity();
    }
    catch (theError)
    {
        break;
    }
}
```

**Comment by Rusketh** [comment]
Break is for switch and loops, not for use with try catch.
that is not a feature of this language.

**Comment by Rusketh** [comment]
My bad, i have now added support for this.
