### ISSUE TITLE
[BUG] Using hologram in Expression 3 leads Validation to Engine Error

### ISSUE THREAD

**Issue by Scors4** [Rusketh/ExpAdv3#39]
Using hologram in Expression 3 leads Validation to Engine Error

Repeated validation will lead to an engine crash if a hologram is used in a decently sized Expression 3 code.  Can't really describe it better than that.

Example code (just keep validating):
https://gist.github.com/Scors4/365a3f5136c32f6ffc1e80c89d2b4a6e

Further testing shows that it's not just holograms:
https://gist.github.com/Scors4/975bc214d70801195ae40f7fe47166dc

**Comment by Rusketh** [comment]
ok, upon investigation it seems that after validating this code about 10 times in SP I can get gmod to hit 3GB+ of ram. It is as if gmod is not garbage collecting.
