### ISSUE TITLE
[BUG] Userclasses cannot be pushed to a table.

### ISSUE THREAD

**Issue by HansLarsen** [Rusketh/ExpAdv3#47]
@name "Generic Gate";
table newTable = new table()
class testClass
{
    testClass() {
        system.out("Hej")
    }
}
function void Main() {
    testClass myTestClass = new testClass()
    newTable.push(myTestClass)
}
Main();

The above code doesn't work, the newTable.push method simply returns an error saying that there is not such a method.
Simularily i am not allowed to cast the user class to a variant.

**Comment by Rusketh** [comment]
Fixed as of like idk 2 days now.
